// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7_PD4BhyG1ZC22Fb6R1KMYTwIowP200',
    appId: '1:867873477247:web:abef48629ef90066eee54a',
    messagingSenderId: '867873477247',
    projectId: 'tiktok-flutter-84b85',
    authDomain: 'tiktok-flutter-84b85.firebaseapp.com',
    storageBucket: 'tiktok-flutter-84b85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuzjOqcOnNP8qL1xlOS_fuJdCTU4B_aTo',
    appId: '1:867873477247:android:40f0da877e1e9e03eee54a',
    messagingSenderId: '867873477247',
    projectId: 'tiktok-flutter-84b85',
    storageBucket: 'tiktok-flutter-84b85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_RYDZsYJQhtrp1Q82nUlDVCRxRGtoSiQ',
    appId: '1:867873477247:ios:c455cbfef504e113eee54a',
    messagingSenderId: '867873477247',
    projectId: 'tiktok-flutter-84b85',
    storageBucket: 'tiktok-flutter-84b85.appspot.com',
    iosBundleId: 'edu.uco.cyang19.tiktokapp',
  );
}
